### PR TITLE
Vg 64 styling for main page

### PR DESCRIPTION
**Pull request by Danback**
* Added styling for main page, including hover effects, color changes and more.
* A new filter bar is now available in the body to filter items on the main page (seperate from the searchbar).
* Styling is done in ProductCard which is then imported to the homeView

### CODE REVIEW

**Comment by Danback** [comment]
Will resolve conflicts

**Comment by Danback** [comment]
Removed footer during work because it was causing issues at the time and forgot to add it back, doing that now, putting this as draft for now until i add it back and resolve all conflicts.

**Comment by marcusju23** [comment]
> Removed footer during work because it was causing issues at the time and forgot to add it back, doing that now, putting this as draft for now until i add it back and resolve all conflicts.

There is already a footer in `App.vue`

**Comment by Danback** [comment]
> > Removed footer during work because it was causing issues at the time and forgot to add it back, doing that now, putting this as draft for now until i add it back and resolve all conflicts.
> 
> There is already a footer in `App.vue`

Not sure why I can't reply directly so I'll write here, I see now that it is present after pulling a later commit, mine was a bit behind.

EDIT: Removed the footer from HomeView

**Comment by Demppas** [comment]
Homepage looks good, nicely done! Aren't the searchbar and the "filterbar" the same thing tho? Maybe we dont need two instances of the same operation!? alternatively we add categories in form of dropdown or checkboxes instead? Maybe just implement a second navbar where we have categorie listed?

If i search in the filterbar for an item that belongs to a category further down on the page it doesnt show on the main page until u scroll down. Thats because all the categorys still shows that has no products. Is there someway that we can make the categories that doesnt show products disappear when using filter?

**Review by marcusju23 — CHANGES_REQUESTED** [review]
`ProductDetailView.vue`:
- It looks unfinished in `ProductDetailView.vue`. The cards are clipping into each other etc. 

`HomeView.vue`:
- It would also be nice to just be able to click on the card in `HomeView.vue` instead of having to click on "**View Product**", it also takes up a significant amount of space. 
- Also a minor thing is that the image clips into the container whenever you hover over a product.
- The "Filter Products" is a redundant feature. This is something that maybe could be added to the search in navbar instead?

Other than that it looks great! 👍

**Comment by Danback** [comment]
@marcusju23 @Demppas Working on changes right now.
As for the ProductDetailView.vue issues I am unsure what you mean to be honest. The clipping thing wasn't something I had noticed but I can change it. I can also add so that pressing the whole image directs you to the product, what worries me is that the HomeView products will look a bit empty without the view product button, however we could change this button to say "Add to cart" perhaps?

**Review by marcusju23 — APPROVED** [review]
Checked it out and it looks great! 👍

**Review by Rishad11 — APPROVED** [review]
Tested and it looks really good now, I like the addition of the new filter.

**Pull request merged**
