### PR TITLE
Vg 36 fix merge issues with vg 30 and vg 13

### PR DESCRIPTION
**Pull request by marcusju23**
Solves merge issues and closes #21 and #22.

### CODE REVIEW

**Review by Danback — DISMISSED** [review]
Very nice, this was important to prevent clashing, good job!

**Review by Demppas — COMMENTED** [review]
**Comment for ProductDetailView**

Optionally we can add a error handling for when products are not fetchd correctly:
  try {
    const id = route.params.id;
    product.value = await apiService.getProductById(id);
  } catch (error) {
    console.error('Error fetching product:', error);
  }

We can also check that the product image isnt null by adding:
product image**

This ensures that the image element is only rendered if a product image exist and has atleast one item.

**Review by Demppas — DISMISSED** [review]
All for all everything looks fine. See other comments for optional adjustment.

**Review by Demppas — DISMISSED** [review]
nice!

**Review by Demppas — DISMISSED** [review]

**Review by Danback — DISMISSED** [review]
Nice!

**Review by Demppas — APPROVED** [review]
yup

**Review by Danback — APPROVED** [review]
Looks good!

**Pull request merged**
